### ISSUE TITLE
repo name change to just "google"

### ISSUE THREAD

**Issue by thedoubl3j** [ansible-collections/google#157]
##### SUMMARY

As this repo now lives in a organization call "ansible-collections", might be worth it just to change the name of the repo to just "google" and remove the "ansible_collections" prefix.

**Comment by thedoubl3j** [comment]
bumping this

**Comment by gundalow** [comment]
@rambleraptor @erjohnso Hi, can we rename this repo to `google.cloud` (namespace.collection) to match the standard naming convention we have?

**Comment by rambleraptor** [comment]
Sorry about not noticing this! Yeah, that sounds great.

**Comment by ericsysmin** [comment]
+1 for this :)

**Comment by rambleraptor** [comment]
Fixed!

**Comment by gundalow** [comment]
renamed
You will want to update your git remotes https://help.github.com/en/github/administering-a-repository/renaming-a-repository
